### ISSUE TITLE
Refactor proposal `DATE_TO_PARTS`

### ISSUE THREAD

**Issue by Serhioromano** [WengerAG/structured-text-utilities#3]
First function to refactor I want `DATE_TO_PARTS`. It looks like there are huge misconceptions. There are `FOR` cycle for years and in every year 12 `FOR` cycles for each month. That is quite a load.

This function does not return an array, and I do not see reasons to have nested cycle. I can get rid of it completely and greatly optimize this function.

**Comment by andyruckstuhl** [comment]
Thank you for your interest and your participation - I appreciate that!

Please take another look at the code. In fact, there isn't a nested loop: if the target year isn't reached, the inner loop won't be executed at all.

Nevertheless, if you are able to create a faster code, please go on and send me a PR.

**Comment by Serhioromano** [comment]
Good. As soon as you accept my current PR.
